spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=aluno
    username: root
    password: root
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
